# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GERICS_ERA5_DownloadMask.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DownloadTool(object):
    def setupUi(self, DownloadTool):
        DownloadTool.setObjectName("DownloadTool")
        DownloadTool.resize(1127, 898)
        font = QtGui.QFont()
        font.setPointSize(12)
        DownloadTool.setFont(font)
        self.centralwidget = QtWidgets.QWidget(DownloadTool)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 231, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.t2m = QtWidgets.QRadioButton(self.centralwidget)
        self.t2m.setGeometry(QtCore.QRect(170, 90, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t2m.setFont(font)
        self.t2m.setObjectName("t2m")
        self.variables_era = QtWidgets.QButtonGroup(DownloadTool)
        self.variables_era.setObjectName("variables_era")
        self.variables_era.addButton(self.t2m)
        self.d2m = QtWidgets.QRadioButton(self.centralwidget)
        self.d2m.setGeometry(QtCore.QRect(170, 120, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.d2m.setFont(font)
        self.d2m.setObjectName("d2m")
        self.variables_era.addButton(self.d2m)
        self.mslp = QtWidgets.QRadioButton(self.centralwidget)
        self.mslp.setGeometry(QtCore.QRect(170, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mslp.setFont(font)
        self.mslp.setObjectName("mslp")
        self.variables_era.addButton(self.mslp)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(26, 230, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.allyears = QtWidgets.QCheckBox(self.centralwidget)
        self.allyears.setGeometry(QtCore.QRect(150, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.allyears.setFont(font)
        self.allyears.setObjectName("allyears")
        self.y2020 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2020.setGeometry(QtCore.QRect(250, 230, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2020.setFont(font)
        self.y2020.setObjectName("y2020")
        self.y2019 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2019.setGeometry(QtCore.QRect(320, 230, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2019.setFont(font)
        self.y2019.setObjectName("y2019")
        self.y2018 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2018.setGeometry(QtCore.QRect(390, 230, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2018.setFont(font)
        self.y2018.setObjectName("y2018")
        self.y2016 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2016.setGeometry(QtCore.QRect(530, 230, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2016.setFont(font)
        self.y2016.setObjectName("y2016")
        self.y2015 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2015.setGeometry(QtCore.QRect(600, 230, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2015.setFont(font)
        self.y2015.setObjectName("y2015")
        self.y2012 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2012.setGeometry(QtCore.QRect(810, 230, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2012.setFont(font)
        self.y2012.setObjectName("y2012")
        self.y2017 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2017.setGeometry(QtCore.QRect(460, 230, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2017.setFont(font)
        self.y2017.setObjectName("y2017")
        self.y2014 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2014.setGeometry(QtCore.QRect(670, 230, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2014.setFont(font)
        self.y2014.setObjectName("y2014")
        self.y2011 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2011.setGeometry(QtCore.QRect(880, 230, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2011.setFont(font)
        self.y2011.setObjectName("y2011")
        self.y2008 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2008.setGeometry(QtCore.QRect(150, 260, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2008.setFont(font)
        self.y2008.setObjectName("y2008")
        self.y2007 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2007.setGeometry(QtCore.QRect(220, 260, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2007.setFont(font)
        self.y2007.setObjectName("y2007")
        self.y2013 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2013.setGeometry(QtCore.QRect(740, 230, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2013.setFont(font)
        self.y2013.setObjectName("y2013")
        self.y2002 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2002.setGeometry(QtCore.QRect(570, 260, 70, 21))
        self.y2002.setObjectName("y2002")
        self.y2003 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2003.setGeometry(QtCore.QRect(500, 260, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2003.setFont(font)
        self.y2003.setObjectName("y2003")
        self.y2010 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2010.setGeometry(QtCore.QRect(950, 230, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2010.setFont(font)
        self.y2010.setObjectName("y2010")
        self.y2009 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2009.setGeometry(QtCore.QRect(1020, 230, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2009.setFont(font)
        self.y2009.setObjectName("y2009")
        self.y2004 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2004.setGeometry(QtCore.QRect(430, 260, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2004.setFont(font)
        self.y2004.setObjectName("y2004")
        self.y2005 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2005.setGeometry(QtCore.QRect(360, 260, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2005.setFont(font)
        self.y2005.setObjectName("y2005")
        self.y2006 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2006.setGeometry(QtCore.QRect(290, 260, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2006.setFont(font)
        self.y2006.setObjectName("y2006")
        self.y2001 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2001.setGeometry(QtCore.QRect(640, 260, 70, 21))
        self.y2001.setObjectName("y2001")
        self.y2000 = QtWidgets.QCheckBox(self.centralwidget)
        self.y2000.setGeometry(QtCore.QRect(710, 260, 70, 21))
        self.y2000.setObjectName("y2000")
        self.y1994 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1994.setGeometry(QtCore.QRect(220, 290, 61, 21))
        self.y1994.setObjectName("y1994")
        self.y1999 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1999.setGeometry(QtCore.QRect(780, 260, 70, 21))
        self.y1999.setObjectName("y1999")
        self.y1998 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1998.setGeometry(QtCore.QRect(850, 260, 70, 21))
        self.y1998.setObjectName("y1998")
        self.y1995 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1995.setGeometry(QtCore.QRect(150, 290, 70, 21))
        self.y1995.setObjectName("y1995")
        self.y1985 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1985.setGeometry(QtCore.QRect(850, 290, 70, 21))
        self.y1985.setObjectName("y1985")
        self.y1987 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1987.setGeometry(QtCore.QRect(710, 290, 61, 21))
        self.y1987.setObjectName("y1987")
        self.y1989 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1989.setGeometry(QtCore.QRect(570, 290, 70, 21))
        self.y1989.setObjectName("y1989")
        self.y1996 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1996.setGeometry(QtCore.QRect(990, 260, 70, 21))
        self.y1996.setObjectName("y1996")
        self.y1988 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1988.setGeometry(QtCore.QRect(640, 290, 70, 21))
        self.y1988.setObjectName("y1988")
        self.y1986 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1986.setGeometry(QtCore.QRect(780, 290, 70, 21))
        self.y1986.setObjectName("y1986")
        self.y1990 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1990.setGeometry(QtCore.QRect(500, 290, 70, 21))
        self.y1990.setObjectName("y1990")
        self.y1983 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1983.setGeometry(QtCore.QRect(990, 290, 70, 21))
        self.y1983.setObjectName("y1983")
        self.y1984 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1984.setGeometry(QtCore.QRect(920, 290, 70, 21))
        self.y1984.setObjectName("y1984")
        self.y1991 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1991.setGeometry(QtCore.QRect(430, 290, 70, 21))
        self.y1991.setObjectName("y1991")
        self.y1993 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1993.setGeometry(QtCore.QRect(290, 290, 70, 21))
        self.y1993.setObjectName("y1993")
        self.y1997 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1997.setGeometry(QtCore.QRect(920, 260, 70, 21))
        self.y1997.setObjectName("y1997")
        self.y1992 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1992.setGeometry(QtCore.QRect(360, 290, 70, 21))
        self.y1992.setObjectName("y1992")
        self.y1982 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1982.setGeometry(QtCore.QRect(150, 320, 70, 21))
        self.y1982.setObjectName("y1982")
        self.y1981 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1981.setGeometry(QtCore.QRect(220, 320, 70, 21))
        self.y1981.setObjectName("y1981")
        self.y1980 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1980.setGeometry(QtCore.QRect(290, 320, 70, 21))
        self.y1980.setObjectName("y1980")
        self.y1979 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1979.setGeometry(QtCore.QRect(360, 320, 70, 21))
        self.y1979.setObjectName("y1979")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 400, 121, 21))
        self.label_5.setObjectName("label_5")
        self.allmonths = QtWidgets.QCheckBox(self.centralwidget)
        self.allmonths.setGeometry(QtCore.QRect(150, 400, 101, 17))
        self.allmonths.setObjectName("allmonths")
        self.m_jan = QtWidgets.QCheckBox(self.centralwidget)
        self.m_jan.setGeometry(QtCore.QRect(260, 400, 101, 17))
        self.m_jan.setObjectName("m_jan")
        self.m_feb = QtWidgets.QCheckBox(self.centralwidget)
        self.m_feb.setGeometry(QtCore.QRect(350, 400, 101, 21))
        self.m_feb.setObjectName("m_feb")
        self.m_mar = QtWidgets.QCheckBox(self.centralwidget)
        self.m_mar.setGeometry(QtCore.QRect(450, 400, 70, 21))
        self.m_mar.setObjectName("m_mar")
        self.m_apr = QtWidgets.QCheckBox(self.centralwidget)
        self.m_apr.setGeometry(QtCore.QRect(530, 400, 70, 21))
        self.m_apr.setObjectName("m_apr")
        self.m_may = QtWidgets.QCheckBox(self.centralwidget)
        self.m_may.setGeometry(QtCore.QRect(600, 400, 70, 21))
        self.m_may.setObjectName("m_may")
        self.m_jun = QtWidgets.QCheckBox(self.centralwidget)
        self.m_jun.setGeometry(QtCore.QRect(660, 400, 70, 21))
        self.m_jun.setObjectName("m_jun")
        self.m_jul = QtWidgets.QCheckBox(self.centralwidget)
        self.m_jul.setGeometry(QtCore.QRect(730, 400, 70, 21))
        self.m_jul.setObjectName("m_jul")
        self.m_aug = QtWidgets.QCheckBox(self.centralwidget)
        self.m_aug.setGeometry(QtCore.QRect(800, 400, 81, 21))
        self.m_aug.setObjectName("m_aug")
        self.m_sep = QtWidgets.QCheckBox(self.centralwidget)
        self.m_sep.setGeometry(QtCore.QRect(890, 400, 101, 21))
        self.m_sep.setObjectName("m_sep")
        self.m_oct = QtWidgets.QCheckBox(self.centralwidget)
        self.m_oct.setGeometry(QtCore.QRect(150, 430, 91, 21))
        self.m_oct.setObjectName("m_oct")
        self.m_nov = QtWidgets.QCheckBox(self.centralwidget)
        self.m_nov.setGeometry(QtCore.QRect(250, 430, 111, 21))
        self.m_nov.setObjectName("m_nov")
        self.m_dec = QtWidgets.QCheckBox(self.centralwidget)
        self.m_dec.setGeometry(QtCore.QRect(360, 430, 111, 21))
        self.m_dec.setObjectName("m_dec")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 510, 111, 21))
        self.label_6.setObjectName("label_6")
        self.alldays = QtWidgets.QCheckBox(self.centralwidget)
        self.alldays.setGeometry(QtCore.QRect(150, 510, 82, 21))
        self.alldays.setObjectName("alldays")
        self.d_03 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_03.setGeometry(QtCore.QRect(350, 510, 70, 21))
        self.d_03.setObjectName("d_03")
        self.d_18 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_18.setGeometry(QtCore.QRect(200, 540, 70, 21))
        self.d_18.setObjectName("d_18")
        self.d_01 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_01.setGeometry(QtCore.QRect(250, 510, 70, 21))
        self.d_01.setObjectName("d_01")
        self.d_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_12.setGeometry(QtCore.QRect(800, 510, 70, 21))
        self.d_12.setObjectName("d_12")
        self.d_06 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_06.setGeometry(QtCore.QRect(500, 510, 70, 21))
        self.d_06.setObjectName("d_06")
        self.d_02 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_02.setGeometry(QtCore.QRect(300, 510, 70, 21))
        self.d_02.setObjectName("d_02")
        self.d_23 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_23.setGeometry(QtCore.QRect(450, 540, 70, 21))
        self.d_23.setObjectName("d_23")
        self.d_20 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_20.setGeometry(QtCore.QRect(300, 540, 70, 21))
        self.d_20.setObjectName("d_20")
        self.d_04 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_04.setGeometry(QtCore.QRect(400, 510, 70, 21))
        self.d_04.setObjectName("d_04")
        self.d_05 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_05.setGeometry(QtCore.QRect(450, 510, 70, 21))
        self.d_05.setObjectName("d_05")
        self.d_14 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_14.setGeometry(QtCore.QRect(900, 510, 70, 21))
        self.d_14.setObjectName("d_14")
        self.d_21 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_21.setGeometry(QtCore.QRect(350, 540, 70, 21))
        self.d_21.setObjectName("d_21")
        self.d_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_10.setGeometry(QtCore.QRect(700, 510, 70, 21))
        self.d_10.setObjectName("d_10")
        self.d_15 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_15.setGeometry(QtCore.QRect(950, 510, 70, 21))
        self.d_15.setObjectName("d_15")
        self.d_08 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_08.setGeometry(QtCore.QRect(600, 510, 70, 21))
        self.d_08.setObjectName("d_08")
        self.d_17 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_17.setGeometry(QtCore.QRect(150, 540, 70, 21))
        self.d_17.setObjectName("d_17")
        self.d_22 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_22.setGeometry(QtCore.QRect(400, 540, 70, 21))
        self.d_22.setObjectName("d_22")
        self.d_19 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_19.setGeometry(QtCore.QRect(250, 540, 70, 21))
        self.d_19.setObjectName("d_19")
        self.d_09 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_09.setGeometry(QtCore.QRect(650, 510, 70, 21))
        self.d_09.setObjectName("d_09")
        self.d_13 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_13.setGeometry(QtCore.QRect(850, 510, 70, 21))
        self.d_13.setObjectName("d_13")
        self.d_07 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_07.setGeometry(QtCore.QRect(550, 510, 70, 21))
        self.d_07.setObjectName("d_07")
        self.d_16 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_16.setGeometry(QtCore.QRect(1000, 510, 70, 21))
        self.d_16.setObjectName("d_16")
        self.d_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_11.setGeometry(QtCore.QRect(750, 510, 70, 21))
        self.d_11.setObjectName("d_11")
        self.d_24 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_24.setGeometry(QtCore.QRect(500, 540, 70, 21))
        self.d_24.setObjectName("d_24")
        self.d_25 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_25.setGeometry(QtCore.QRect(550, 540, 70, 21))
        self.d_25.setObjectName("d_25")
        self.d_26 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_26.setGeometry(QtCore.QRect(600, 540, 70, 21))
        self.d_26.setObjectName("d_26")
        self.d_27 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_27.setGeometry(QtCore.QRect(650, 540, 70, 21))
        self.d_27.setObjectName("d_27")
        self.d_28 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_28.setGeometry(QtCore.QRect(700, 540, 70, 21))
        self.d_28.setObjectName("d_28")
        self.d_29 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_29.setGeometry(QtCore.QRect(750, 540, 70, 21))
        self.d_29.setObjectName("d_29")
        self.d_30 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_30.setGeometry(QtCore.QRect(800, 540, 70, 21))
        self.d_30.setObjectName("d_30")
        self.d_31 = QtWidgets.QCheckBox(self.centralwidget)
        self.d_31.setGeometry(QtCore.QRect(850, 540, 70, 21))
        self.d_31.setObjectName("d_31")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 620, 101, 16))
        self.label_8.setObjectName("label_8")
        self.alltimes = QtWidgets.QCheckBox(self.centralwidget)
        self.alltimes.setGeometry(QtCore.QRect(150, 620, 101, 21))
        self.alltimes.setObjectName("alltimes")
        self.t_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_5.setGeometry(QtCore.QRect(650, 620, 70, 21))
        self.t_5.setObjectName("t_5")
        self.t_0 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_0.setGeometry(QtCore.QRect(250, 620, 70, 21))
        self.t_0.setObjectName("t_0")
        self.t_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_2.setGeometry(QtCore.QRect(410, 620, 70, 21))
        self.t_2.setObjectName("t_2")
        self.t_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_6.setGeometry(QtCore.QRect(730, 620, 70, 21))
        self.t_6.setObjectName("t_6")
        self.t_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_7.setGeometry(QtCore.QRect(810, 620, 70, 21))
        self.t_7.setObjectName("t_7")
        self.t_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_4.setGeometry(QtCore.QRect(570, 620, 70, 21))
        self.t_4.setObjectName("t_4")
        self.t_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_1.setGeometry(QtCore.QRect(330, 620, 70, 21))
        self.t_1.setObjectName("t_1")
        self.t_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_3.setGeometry(QtCore.QRect(490, 620, 70, 21))
        self.t_3.setObjectName("t_3")
        self.t_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_10.setGeometry(QtCore.QRect(150, 650, 70, 21))
        self.t_10.setObjectName("t_10")
        self.t_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_11.setGeometry(QtCore.QRect(230, 650, 70, 21))
        self.t_11.setObjectName("t_11")
        self.t_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_12.setGeometry(QtCore.QRect(310, 650, 70, 21))
        self.t_12.setObjectName("t_12")
        self.t_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_8.setGeometry(QtCore.QRect(890, 620, 70, 21))
        self.t_8.setObjectName("t_8")
        self.t_13 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_13.setGeometry(QtCore.QRect(390, 650, 70, 21))
        self.t_13.setObjectName("t_13")
        self.t_15 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_15.setGeometry(QtCore.QRect(550, 650, 70, 21))
        self.t_15.setObjectName("t_15")
        self.t_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_9.setGeometry(QtCore.QRect(970, 620, 70, 21))
        self.t_9.setObjectName("t_9")
        self.t_14 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_14.setGeometry(QtCore.QRect(470, 650, 70, 21))
        self.t_14.setObjectName("t_14")
        self.t_16 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_16.setGeometry(QtCore.QRect(630, 650, 70, 21))
        self.t_16.setObjectName("t_16")
        self.t_20 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_20.setGeometry(QtCore.QRect(950, 650, 70, 21))
        self.t_20.setObjectName("t_20")
        self.t_19 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_19.setGeometry(QtCore.QRect(870, 650, 70, 21))
        self.t_19.setObjectName("t_19")
        self.t_18 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_18.setGeometry(QtCore.QRect(790, 650, 70, 21))
        self.t_18.setObjectName("t_18")
        self.t_17 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_17.setGeometry(QtCore.QRect(710, 650, 70, 21))
        self.t_17.setObjectName("t_17")
        self.t_23 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_23.setGeometry(QtCore.QRect(310, 680, 70, 21))
        self.t_23.setObjectName("t_23")
        self.t_22 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_22.setGeometry(QtCore.QRect(230, 680, 70, 21))
        self.t_22.setObjectName("t_22")
        self.t_21 = QtWidgets.QCheckBox(self.centralwidget)
        self.t_21.setGeometry(QtCore.QRect(150, 680, 70, 21))
        self.t_21.setObjectName("t_21")
        self.starter = QtWidgets.QPushButton(self.centralwidget)
        self.starter.setGeometry(QtCore.QRect(60, 750, 151, 81))
        self.starter.setObjectName("starter")
        self.fname = QtWidgets.QLineEdit(self.centralwidget)
        self.fname.setGeometry(QtCore.QRect(410, 760, 321, 31))
        self.fname.setObjectName("fname")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(270, 760, 131, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(750, 763, 181, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 640, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(280, 790, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 130, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.resett = QtWidgets.QPushButton(self.centralwidget)
        self.resett.setGeometry(QtCore.QRect(980, 750, 121, 71))
        self.resett.setObjectName("resett")
        self.sst = QtWidgets.QRadioButton(self.centralwidget)
        self.sst.setGeometry(QtCore.QRect(340, 90, 161, 21))
        self.sst.setObjectName("sst")
        self.variables_era.addButton(self.sst)
        self.surfpres = QtWidgets.QRadioButton(self.centralwidget)
        self.surfpres.setGeometry(QtCore.QRect(340, 120, 141, 21))
        self.surfpres.setObjectName("surfpres")
        self.variables_era.addButton(self.surfpres)
        self.totalprec = QtWidgets.QRadioButton(self.centralwidget)
        self.totalprec.setGeometry(QtCore.QRect(340, 150, 161, 21))
        self.totalprec.setObjectName("totalprec")
        self.variables_era.addButton(self.totalprec)
        self.u10wind = QtWidgets.QRadioButton(self.centralwidget)
        self.u10wind.setGeometry(QtCore.QRect(520, 90, 121, 21))
        self.u10wind.setObjectName("u10wind")
        self.variables_era.addButton(self.u10wind)
        self.v10wind = QtWidgets.QRadioButton(self.centralwidget)
        self.v10wind.setGeometry(QtCore.QRect(520, 120, 121, 21))
        self.v10wind.setObjectName("v10wind")
        self.variables_era.addButton(self.v10wind)
        self.modell = QtWidgets.QComboBox(self.centralwidget)
        self.modell.setGeometry(QtCore.QRect(170, 10, 331, 31))
        self.modell.setObjectName("modell")
        self.modell.addItem("")
        self.modell.addItem("")
        self.modell.addItem("")
        self.modell.addItem("")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(350, 65, 121, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(780, 70, 131, 21))
        self.label_15.setObjectName("label_15")
        self.uer_t2m = QtWidgets.QRadioButton(self.centralwidget)
        self.uer_t2m.setGeometry(QtCore.QRect(710, 90, 141, 21))
        self.uer_t2m.setObjectName("uer_t2m")
        self.variables_uer = QtWidgets.QButtonGroup(DownloadTool)
        self.variables_uer.setObjectName("variables_uer")
        self.variables_uer.addButton(self.uer_t2m)
        self.uer_rh = QtWidgets.QRadioButton(self.centralwidget)
        self.uer_rh.setGeometry(QtCore.QRect(710, 120, 181, 21))
        self.uer_rh.setObjectName("uer_rh")
        self.variables_uer.addButton(self.uer_rh)
        self.uer_totprec = QtWidgets.QRadioButton(self.centralwidget)
        self.uer_totprec.setGeometry(QtCore.QRect(710, 150, 161, 21))
        self.uer_totprec.setObjectName("uer_totprec")
        self.variables_uer.addButton(self.uer_totprec)
        self.uer_mslp = QtWidgets.QRadioButton(self.centralwidget)
        self.uer_mslp.setGeometry(QtCore.QRect(920, 90, 82, 21))
        self.uer_mslp.setObjectName("uer_mslp")
        self.variables_uer.addButton(self.uer_mslp)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(140, 200, 471, 21))
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(150, 480, 281, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(150, 590, 911, 21))
        self.label_17.setObjectName("label_17")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(643, 60, 31, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dotag = QtWidgets.QDateEdit(self.centralwidget)
        self.dotag.setGeometry(QtCore.QRect(690, 10, 111, 31))
        self.dotag.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dotag.setObjectName("dotag")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(550, 20, 121, 16))
        self.label_18.setObjectName("label_18")
        self.y1978 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1978.setGeometry(QtCore.QRect(430, 320, 71, 21))
        self.y1978.setObjectName("y1978")
        self.y1970 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1970.setGeometry(QtCore.QRect(990, 320, 70, 21))
        self.y1970.setObjectName("y1970")
        self.y1971 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1971.setGeometry(QtCore.QRect(920, 320, 70, 21))
        self.y1971.setObjectName("y1971")
        self.y1972 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1972.setGeometry(QtCore.QRect(850, 320, 70, 21))
        self.y1972.setObjectName("y1972")
        self.y1976 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1976.setGeometry(QtCore.QRect(570, 320, 70, 21))
        self.y1976.setObjectName("y1976")
        self.y1975 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1975.setGeometry(QtCore.QRect(640, 320, 70, 21))
        self.y1975.setObjectName("y1975")
        self.y1974 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1974.setGeometry(QtCore.QRect(710, 320, 70, 21))
        self.y1974.setObjectName("y1974")
        self.y1973 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1973.setGeometry(QtCore.QRect(780, 320, 70, 21))
        self.y1973.setObjectName("y1973")
        self.y1977 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1977.setGeometry(QtCore.QRect(500, 320, 70, 21))
        self.y1977.setObjectName("y1977")
        self.y1969 = QtWidgets.QCheckBox(self.centralwidget)
        self.y1969.setGeometry(QtCore.QRect(150, 350, 70, 21))
        self.y1969.setObjectName("y1969")
        DownloadTool.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DownloadTool)
        self.statusbar.setObjectName("statusbar")
        DownloadTool.setStatusBar(self.statusbar)

        self.retranslateUi(DownloadTool)
        QtCore.QMetaObject.connectSlotsByName(DownloadTool)

    def retranslateUi(self, DownloadTool):
        _translate = QtCore.QCoreApplication.translate
        DownloadTool.setWindowTitle(_translate("DownloadTool", "MainWindow"))
        self.label.setText(_translate("DownloadTool", "Download Tool for:"))
        self.label_2.setText(_translate("DownloadTool", "Choose Variable:"))
        self.t2m.setText(_translate("DownloadTool", "Temperature 2m"))
        self.d2m.setText(_translate("DownloadTool", "Dewpoint 2m"))
        self.mslp.setText(_translate("DownloadTool", "MSLP"))
        self.label_3.setText(_translate("DownloadTool", "Chosse Year:"))
        self.label_4.setText(_translate("DownloadTool", "Note: Boxes are grouped."))
        self.allyears.setText(_translate("DownloadTool", "All Years"))
        self.y2020.setText(_translate("DownloadTool", "2020"))
        self.y2019.setText(_translate("DownloadTool", "2019"))
        self.y2018.setText(_translate("DownloadTool", "2018"))
        self.y2016.setText(_translate("DownloadTool", "2016"))
        self.y2015.setText(_translate("DownloadTool", "2015"))
        self.y2012.setText(_translate("DownloadTool", "2012"))
        self.y2017.setText(_translate("DownloadTool", "2017"))
        self.y2014.setText(_translate("DownloadTool", "2014"))
        self.y2011.setText(_translate("DownloadTool", "2011"))
        self.y2008.setText(_translate("DownloadTool", "2008"))
        self.y2007.setText(_translate("DownloadTool", "2007"))
        self.y2013.setText(_translate("DownloadTool", "2013"))
        self.y2002.setText(_translate("DownloadTool", "2002"))
        self.y2003.setText(_translate("DownloadTool", "2003"))
        self.y2010.setText(_translate("DownloadTool", "2010"))
        self.y2009.setText(_translate("DownloadTool", "2009"))
        self.y2004.setText(_translate("DownloadTool", "2004"))
        self.y2005.setText(_translate("DownloadTool", "2005"))
        self.y2006.setText(_translate("DownloadTool", "2006"))
        self.y2001.setText(_translate("DownloadTool", "2001"))
        self.y2000.setText(_translate("DownloadTool", "2000"))
        self.y1994.setText(_translate("DownloadTool", "1994"))
        self.y1999.setText(_translate("DownloadTool", "1999"))
        self.y1998.setText(_translate("DownloadTool", "1998"))
        self.y1995.setText(_translate("DownloadTool", "1995"))
        self.y1985.setText(_translate("DownloadTool", "1985"))
        self.y1987.setText(_translate("DownloadTool", "1987"))
        self.y1989.setText(_translate("DownloadTool", "1989"))
        self.y1996.setText(_translate("DownloadTool", "1996"))
        self.y1988.setText(_translate("DownloadTool", "1988"))
        self.y1986.setText(_translate("DownloadTool", "1986"))
        self.y1990.setText(_translate("DownloadTool", "1990"))
        self.y1983.setText(_translate("DownloadTool", "1983"))
        self.y1984.setText(_translate("DownloadTool", "1984"))
        self.y1991.setText(_translate("DownloadTool", "1991"))
        self.y1993.setText(_translate("DownloadTool", "1993"))
        self.y1997.setText(_translate("DownloadTool", "1997"))
        self.y1992.setText(_translate("DownloadTool", "1992"))
        self.y1982.setText(_translate("DownloadTool", "1982"))
        self.y1981.setText(_translate("DownloadTool", "1981"))
        self.y1980.setText(_translate("DownloadTool", "1980"))
        self.y1979.setText(_translate("DownloadTool", "1979"))
        self.label_5.setText(_translate("DownloadTool", "Choose Month:"))
        self.allmonths.setText(_translate("DownloadTool", "All Months"))
        self.m_jan.setText(_translate("DownloadTool", "January"))
        self.m_feb.setText(_translate("DownloadTool", "February"))
        self.m_mar.setText(_translate("DownloadTool", "March"))
        self.m_apr.setText(_translate("DownloadTool", "April"))
        self.m_may.setText(_translate("DownloadTool", "May"))
        self.m_jun.setText(_translate("DownloadTool", "June"))
        self.m_jul.setText(_translate("DownloadTool", "July"))
        self.m_aug.setText(_translate("DownloadTool", "August"))
        self.m_sep.setText(_translate("DownloadTool", "September"))
        self.m_oct.setText(_translate("DownloadTool", "October"))
        self.m_nov.setText(_translate("DownloadTool", "November"))
        self.m_dec.setText(_translate("DownloadTool", "December"))
        self.label_6.setText(_translate("DownloadTool", "Choose Day:"))
        self.alldays.setText(_translate("DownloadTool", "All Days"))
        self.d_03.setText(_translate("DownloadTool", "03"))
        self.d_18.setText(_translate("DownloadTool", "18"))
        self.d_01.setText(_translate("DownloadTool", "01"))
        self.d_12.setText(_translate("DownloadTool", "12"))
        self.d_06.setText(_translate("DownloadTool", "06"))
        self.d_02.setText(_translate("DownloadTool", "02"))
        self.d_23.setText(_translate("DownloadTool", "23"))
        self.d_20.setText(_translate("DownloadTool", "20"))
        self.d_04.setText(_translate("DownloadTool", "04"))
        self.d_05.setText(_translate("DownloadTool", "05"))
        self.d_14.setText(_translate("DownloadTool", "14"))
        self.d_21.setText(_translate("DownloadTool", "21"))
        self.d_10.setText(_translate("DownloadTool", "10"))
        self.d_15.setText(_translate("DownloadTool", "15"))
        self.d_08.setText(_translate("DownloadTool", "08"))
        self.d_17.setText(_translate("DownloadTool", "17"))
        self.d_22.setText(_translate("DownloadTool", "22"))
        self.d_19.setText(_translate("DownloadTool", "19"))
        self.d_09.setText(_translate("DownloadTool", "09"))
        self.d_13.setText(_translate("DownloadTool", "13"))
        self.d_07.setText(_translate("DownloadTool", "07"))
        self.d_16.setText(_translate("DownloadTool", "16"))
        self.d_11.setText(_translate("DownloadTool", "11"))
        self.d_24.setText(_translate("DownloadTool", "24"))
        self.d_25.setText(_translate("DownloadTool", "25"))
        self.d_26.setText(_translate("DownloadTool", "26"))
        self.d_27.setText(_translate("DownloadTool", "27"))
        self.d_28.setText(_translate("DownloadTool", "28"))
        self.d_29.setText(_translate("DownloadTool", "29"))
        self.d_30.setText(_translate("DownloadTool", "30"))
        self.d_31.setText(_translate("DownloadTool", "31"))
        self.label_8.setText(_translate("DownloadTool", "Choose Time:"))
        self.alltimes.setText(_translate("DownloadTool", "All Times"))
        self.t_5.setText(_translate("DownloadTool", "05:00"))
        self.t_0.setText(_translate("DownloadTool", "00:00"))
        self.t_2.setText(_translate("DownloadTool", "02:00"))
        self.t_6.setText(_translate("DownloadTool", "06:00"))
        self.t_7.setText(_translate("DownloadTool", "07:00"))
        self.t_4.setText(_translate("DownloadTool", "04:00"))
        self.t_1.setText(_translate("DownloadTool", "01:00"))
        self.t_3.setText(_translate("DownloadTool", "03:00"))
        self.t_10.setText(_translate("DownloadTool", "10:00"))
        self.t_11.setText(_translate("DownloadTool", "11:00"))
        self.t_12.setText(_translate("DownloadTool", "12:00"))
        self.t_8.setText(_translate("DownloadTool", "08:00"))
        self.t_13.setText(_translate("DownloadTool", "13:00"))
        self.t_15.setText(_translate("DownloadTool", "15:00"))
        self.t_9.setText(_translate("DownloadTool", "09:00"))
        self.t_14.setText(_translate("DownloadTool", "14:00"))
        self.t_16.setText(_translate("DownloadTool", "16:00"))
        self.t_20.setText(_translate("DownloadTool", "20:00"))
        self.t_19.setText(_translate("DownloadTool", "19:00"))
        self.t_18.setText(_translate("DownloadTool", "18:00"))
        self.t_17.setText(_translate("DownloadTool", "17:00"))
        self.t_23.setText(_translate("DownloadTool", "23:00"))
        self.t_22.setText(_translate("DownloadTool", "22:00"))
        self.t_21.setText(_translate("DownloadTool", "21:00"))
        self.starter.setText(_translate("DownloadTool", "Start Download"))
        self.label_9.setText(_translate("DownloadTool", "Choose Filename:"))
        self.label_10.setText(_translate("DownloadTool", "(e.g. era5_t2m_12z.nc)"))
        self.label_11.setText(_translate("DownloadTool", "Time in UTC"))
        self.label_12.setText(_translate("DownloadTool", "needs .nc ending"))
        self.label_13.setText(_translate("DownloadTool", "You can just tick one!"))
        self.resett.setText(_translate("DownloadTool", "Reset"))
        self.sst.setText(_translate("DownloadTool", "Sea Surface Temp"))
        self.surfpres.setText(_translate("DownloadTool", "Surface Pressure"))
        self.totalprec.setText(_translate("DownloadTool", "Total Precipitation"))
        self.u10wind.setText(_translate("DownloadTool", "10m u-Wind"))
        self.v10wind.setText(_translate("DownloadTool", "10m v-Wind"))
        self.modell.setItemText(0, _translate("DownloadTool", "ERA5 Hourly Data 1979 - 2020"))
        self.modell.setItemText(1, _translate("DownloadTool", "ERA5 Monthly Data 1979 - 2020"))
        self.modell.setItemText(2, _translate("DownloadTool", "UERRA UERRA-HARMONIE 1969 - 2019"))
        self.modell.setItemText(3, _translate("DownloadTool", "UERRA MESCAN-SURFEX  1969 - 2019"))
        self.label_14.setText(_translate("DownloadTool", "ERA5 Variables:"))
        self.label_15.setText(_translate("DownloadTool", "UERRA Variables:"))
        self.uer_t2m.setText(_translate("DownloadTool", "Temperature 2m"))
        self.uer_rh.setText(_translate("DownloadTool", "Relative Humidity 2m"))
        self.uer_totprec.setText(_translate("DownloadTool", "Total Precipitation"))
        self.uer_mslp.setText(_translate("DownloadTool", "MSLP"))
        self.label_7.setText(_translate("DownloadTool", "Data range:   ERA5 = 1979 - 2020      UERRA = 1969 - 2019:"))
        self.label_16.setText(_translate("DownloadTool", "Day not be choosen for monthly data!"))
        self.label_17.setText(_translate("DownloadTool", "ERA5 hourly: all times available    ERA5 monthly: choose 00:00!    UERRA: 00:00, 06:00, 12:00, 18:00 and all times available"))
        self.label_18.setText(_translate("DownloadTool", "Download Date:"))
        self.y1978.setText(_translate("DownloadTool", "1978"))
        self.y1970.setText(_translate("DownloadTool", "1970"))
        self.y1971.setText(_translate("DownloadTool", "1971"))
        self.y1972.setText(_translate("DownloadTool", "1972"))
        self.y1976.setText(_translate("DownloadTool", "1976"))
        self.y1975.setText(_translate("DownloadTool", "1975"))
        self.y1974.setText(_translate("DownloadTool", "1974"))
        self.y1973.setText(_translate("DownloadTool", "1973"))
        self.y1977.setText(_translate("DownloadTool", "1977"))
        self.y1969.setText(_translate("DownloadTool", "1969"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DownloadTool = QtWidgets.QMainWindow()
    ui = Ui_DownloadTool()
    ui.setupUi(DownloadTool)
    DownloadTool.show()
    sys.exit(app.exec_())

